export default function Head() {
  return (
    <>
      <title>My Eria</title>
      <link rel="manifest" href="/manifest.json" />
      <link rel="apple-touch-icon" href="/logo.png" />
      <link rel="shortcut icon" href="/logo.png" />
      <meta charSet="UTF-8" />
      <meta name="theme-color" content="#fff" />
      <meta name="description" content="Generated by create next app" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
